/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSystemUsersIndexRouteImport } from './routes/dashboard/system-users/index'
import { Route as DashboardShuttleTripsIndexRouteImport } from './routes/dashboard/shuttle-trips/index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard/reports/index'
import { Route as DashboardPaymentsIndexRouteImport } from './routes/dashboard/payments/index'
import { Route as DashboardHireDriverBookingsIndexRouteImport } from './routes/dashboard/hire-driver-bookings/index'
import { Route as DashboardDriversIndexRouteImport } from './routes/dashboard/drivers/index'
import { Route as DashboardCarRentalBookingsIndexRouteImport } from './routes/dashboard/car-rental-bookings/index'
import { Route as DashboardCabTripsIndexRouteImport } from './routes/dashboard/cab-trips/index'
import { Route as DashboardShuttleTripsTripIdIndexRouteImport } from './routes/dashboard/shuttle-trips/$tripId/index'
import { Route as DashboardPricingShuttleIndexRouteImport } from './routes/dashboard/pricing/shuttle/index'
import { Route as DashboardPricingModelIndexRouteImport } from './routes/dashboard/pricing/model/index'
import { Route as DashboardPricingDriverRentalRatesIndexRouteImport } from './routes/dashboard/pricing/driver-rental-rates/index'
import { Route as DashboardPricingCarRentalsIndexRouteImport } from './routes/dashboard/pricing/car-rentals/index'
import { Route as DashboardPricingCabRatesIndexRouteImport } from './routes/dashboard/pricing/cab-rates/index'
import { Route as DashboardHireDriverBookingsBookingIdIndexRouteImport } from './routes/dashboard/hire-driver-bookings/$bookingId/index'
import { Route as DashboardDriversRegisterIndexRouteImport } from './routes/dashboard/drivers/register/index'
import { Route as DashboardDriversDriverIdIndexRouteImport } from './routes/dashboard/drivers/$driverId/index'
import { Route as DashboardCarRentalBookingsSalesPersonnelIndexRouteImport } from './routes/dashboard/car-rental-bookings/sales-personnel/index'
import { Route as DashboardCarRentalBookingsRentalIdIndexRouteImport } from './routes/dashboard/car-rental-bookings/$rentalId/index'
import { Route as DashboardCabTripsTripIdIndexRouteImport } from './routes/dashboard/cab-trips/$tripId/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSystemUsersIndexRoute =
  DashboardSystemUsersIndexRouteImport.update({
    id: '/system-users/',
    path: '/system-users/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardShuttleTripsIndexRoute =
  DashboardShuttleTripsIndexRouteImport.update({
    id: '/shuttle-trips/',
    path: '/shuttle-trips/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsIndexRoute = DashboardPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHireDriverBookingsIndexRoute =
  DashboardHireDriverBookingsIndexRouteImport.update({
    id: '/hire-driver-bookings/',
    path: '/hire-driver-bookings/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDriversIndexRoute = DashboardDriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCarRentalBookingsIndexRoute =
  DashboardCarRentalBookingsIndexRouteImport.update({
    id: '/car-rental-bookings/',
    path: '/car-rental-bookings/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCabTripsIndexRoute = DashboardCabTripsIndexRouteImport.update({
  id: '/cab-trips/',
  path: '/cab-trips/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShuttleTripsTripIdIndexRoute =
  DashboardShuttleTripsTripIdIndexRouteImport.update({
    id: '/shuttle-trips/$tripId/',
    path: '/shuttle-trips/$tripId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPricingShuttleIndexRoute =
  DashboardPricingShuttleIndexRouteImport.update({
    id: '/pricing/shuttle/',
    path: '/pricing/shuttle/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPricingModelIndexRoute =
  DashboardPricingModelIndexRouteImport.update({
    id: '/pricing/model/',
    path: '/pricing/model/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPricingDriverRentalRatesIndexRoute =
  DashboardPricingDriverRentalRatesIndexRouteImport.update({
    id: '/pricing/driver-rental-rates/',
    path: '/pricing/driver-rental-rates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPricingCarRentalsIndexRoute =
  DashboardPricingCarRentalsIndexRouteImport.update({
    id: '/pricing/car-rentals/',
    path: '/pricing/car-rentals/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPricingCabRatesIndexRoute =
  DashboardPricingCabRatesIndexRouteImport.update({
    id: '/pricing/cab-rates/',
    path: '/pricing/cab-rates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardHireDriverBookingsBookingIdIndexRoute =
  DashboardHireDriverBookingsBookingIdIndexRouteImport.update({
    id: '/hire-driver-bookings/$bookingId/',
    path: '/hire-driver-bookings/$bookingId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDriversRegisterIndexRoute =
  DashboardDriversRegisterIndexRouteImport.update({
    id: '/drivers/register/',
    path: '/drivers/register/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDriversDriverIdIndexRoute =
  DashboardDriversDriverIdIndexRouteImport.update({
    id: '/drivers/$driverId/',
    path: '/drivers/$driverId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCarRentalBookingsSalesPersonnelIndexRoute =
  DashboardCarRentalBookingsSalesPersonnelIndexRouteImport.update({
    id: '/car-rental-bookings/sales-personnel/',
    path: '/car-rental-bookings/sales-personnel/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCarRentalBookingsRentalIdIndexRoute =
  DashboardCarRentalBookingsRentalIdIndexRouteImport.update({
    id: '/car-rental-bookings/$rentalId/',
    path: '/car-rental-bookings/$rentalId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCabTripsTripIdIndexRoute =
  DashboardCabTripsTripIdIndexRouteImport.update({
    id: '/cab-trips/$tripId/',
    path: '/cab-trips/$tripId/',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/dashboard/cab-trips/': typeof DashboardCabTripsIndexRoute
  '/dashboard/car-rental-bookings/': typeof DashboardCarRentalBookingsIndexRoute
  '/dashboard/drivers/': typeof DashboardDriversIndexRoute
  '/dashboard/hire-driver-bookings/': typeof DashboardHireDriverBookingsIndexRoute
  '/dashboard/payments/': typeof DashboardPaymentsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/shuttle-trips/': typeof DashboardShuttleTripsIndexRoute
  '/dashboard/system-users/': typeof DashboardSystemUsersIndexRoute
  '/dashboard/cab-trips/$tripId/': typeof DashboardCabTripsTripIdIndexRoute
  '/dashboard/car-rental-bookings/$rentalId/': typeof DashboardCarRentalBookingsRentalIdIndexRoute
  '/dashboard/car-rental-bookings/sales-personnel/': typeof DashboardCarRentalBookingsSalesPersonnelIndexRoute
  '/dashboard/drivers/$driverId/': typeof DashboardDriversDriverIdIndexRoute
  '/dashboard/drivers/register/': typeof DashboardDriversRegisterIndexRoute
  '/dashboard/hire-driver-bookings/$bookingId/': typeof DashboardHireDriverBookingsBookingIdIndexRoute
  '/dashboard/pricing/cab-rates/': typeof DashboardPricingCabRatesIndexRoute
  '/dashboard/pricing/car-rentals/': typeof DashboardPricingCarRentalsIndexRoute
  '/dashboard/pricing/driver-rental-rates/': typeof DashboardPricingDriverRentalRatesIndexRoute
  '/dashboard/pricing/model/': typeof DashboardPricingModelIndexRoute
  '/dashboard/pricing/shuttle/': typeof DashboardPricingShuttleIndexRoute
  '/dashboard/shuttle-trips/$tripId/': typeof DashboardShuttleTripsTripIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/dashboard/cab-trips': typeof DashboardCabTripsIndexRoute
  '/dashboard/car-rental-bookings': typeof DashboardCarRentalBookingsIndexRoute
  '/dashboard/drivers': typeof DashboardDriversIndexRoute
  '/dashboard/hire-driver-bookings': typeof DashboardHireDriverBookingsIndexRoute
  '/dashboard/payments': typeof DashboardPaymentsIndexRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/shuttle-trips': typeof DashboardShuttleTripsIndexRoute
  '/dashboard/system-users': typeof DashboardSystemUsersIndexRoute
  '/dashboard/cab-trips/$tripId': typeof DashboardCabTripsTripIdIndexRoute
  '/dashboard/car-rental-bookings/$rentalId': typeof DashboardCarRentalBookingsRentalIdIndexRoute
  '/dashboard/car-rental-bookings/sales-personnel': typeof DashboardCarRentalBookingsSalesPersonnelIndexRoute
  '/dashboard/drivers/$driverId': typeof DashboardDriversDriverIdIndexRoute
  '/dashboard/drivers/register': typeof DashboardDriversRegisterIndexRoute
  '/dashboard/hire-driver-bookings/$bookingId': typeof DashboardHireDriverBookingsBookingIdIndexRoute
  '/dashboard/pricing/cab-rates': typeof DashboardPricingCabRatesIndexRoute
  '/dashboard/pricing/car-rentals': typeof DashboardPricingCarRentalsIndexRoute
  '/dashboard/pricing/driver-rental-rates': typeof DashboardPricingDriverRentalRatesIndexRoute
  '/dashboard/pricing/model': typeof DashboardPricingModelIndexRoute
  '/dashboard/pricing/shuttle': typeof DashboardPricingShuttleIndexRoute
  '/dashboard/shuttle-trips/$tripId': typeof DashboardShuttleTripsTripIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/dashboard/cab-trips/': typeof DashboardCabTripsIndexRoute
  '/dashboard/car-rental-bookings/': typeof DashboardCarRentalBookingsIndexRoute
  '/dashboard/drivers/': typeof DashboardDriversIndexRoute
  '/dashboard/hire-driver-bookings/': typeof DashboardHireDriverBookingsIndexRoute
  '/dashboard/payments/': typeof DashboardPaymentsIndexRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/shuttle-trips/': typeof DashboardShuttleTripsIndexRoute
  '/dashboard/system-users/': typeof DashboardSystemUsersIndexRoute
  '/dashboard/cab-trips/$tripId/': typeof DashboardCabTripsTripIdIndexRoute
  '/dashboard/car-rental-bookings/$rentalId/': typeof DashboardCarRentalBookingsRentalIdIndexRoute
  '/dashboard/car-rental-bookings/sales-personnel/': typeof DashboardCarRentalBookingsSalesPersonnelIndexRoute
  '/dashboard/drivers/$driverId/': typeof DashboardDriversDriverIdIndexRoute
  '/dashboard/drivers/register/': typeof DashboardDriversRegisterIndexRoute
  '/dashboard/hire-driver-bookings/$bookingId/': typeof DashboardHireDriverBookingsBookingIdIndexRoute
  '/dashboard/pricing/cab-rates/': typeof DashboardPricingCabRatesIndexRoute
  '/dashboard/pricing/car-rentals/': typeof DashboardPricingCarRentalsIndexRoute
  '/dashboard/pricing/driver-rental-rates/': typeof DashboardPricingDriverRentalRatesIndexRoute
  '/dashboard/pricing/model/': typeof DashboardPricingModelIndexRoute
  '/dashboard/pricing/shuttle/': typeof DashboardPricingShuttleIndexRoute
  '/dashboard/shuttle-trips/$tripId/': typeof DashboardShuttleTripsTripIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/signup/'
    | '/dashboard/cab-trips/'
    | '/dashboard/car-rental-bookings/'
    | '/dashboard/drivers/'
    | '/dashboard/hire-driver-bookings/'
    | '/dashboard/payments/'
    | '/dashboard/reports/'
    | '/dashboard/shuttle-trips/'
    | '/dashboard/system-users/'
    | '/dashboard/cab-trips/$tripId/'
    | '/dashboard/car-rental-bookings/$rentalId/'
    | '/dashboard/car-rental-bookings/sales-personnel/'
    | '/dashboard/drivers/$driverId/'
    | '/dashboard/drivers/register/'
    | '/dashboard/hire-driver-bookings/$bookingId/'
    | '/dashboard/pricing/cab-rates/'
    | '/dashboard/pricing/car-rentals/'
    | '/dashboard/pricing/driver-rental-rates/'
    | '/dashboard/pricing/model/'
    | '/dashboard/pricing/shuttle/'
    | '/dashboard/shuttle-trips/$tripId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/cab-trips'
    | '/dashboard/car-rental-bookings'
    | '/dashboard/drivers'
    | '/dashboard/hire-driver-bookings'
    | '/dashboard/payments'
    | '/dashboard/reports'
    | '/dashboard/shuttle-trips'
    | '/dashboard/system-users'
    | '/dashboard/cab-trips/$tripId'
    | '/dashboard/car-rental-bookings/$rentalId'
    | '/dashboard/car-rental-bookings/sales-personnel'
    | '/dashboard/drivers/$driverId'
    | '/dashboard/drivers/register'
    | '/dashboard/hire-driver-bookings/$bookingId'
    | '/dashboard/pricing/cab-rates'
    | '/dashboard/pricing/car-rentals'
    | '/dashboard/pricing/driver-rental-rates'
    | '/dashboard/pricing/model'
    | '/dashboard/pricing/shuttle'
    | '/dashboard/shuttle-trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/dashboard/'
    | '/login/'
    | '/signup/'
    | '/dashboard/cab-trips/'
    | '/dashboard/car-rental-bookings/'
    | '/dashboard/drivers/'
    | '/dashboard/hire-driver-bookings/'
    | '/dashboard/payments/'
    | '/dashboard/reports/'
    | '/dashboard/shuttle-trips/'
    | '/dashboard/system-users/'
    | '/dashboard/cab-trips/$tripId/'
    | '/dashboard/car-rental-bookings/$rentalId/'
    | '/dashboard/car-rental-bookings/sales-personnel/'
    | '/dashboard/drivers/$driverId/'
    | '/dashboard/drivers/register/'
    | '/dashboard/hire-driver-bookings/$bookingId/'
    | '/dashboard/pricing/cab-rates/'
    | '/dashboard/pricing/car-rentals/'
    | '/dashboard/pricing/driver-rental-rates/'
    | '/dashboard/pricing/model/'
    | '/dashboard/pricing/shuttle/'
    | '/dashboard/shuttle-trips/$tripId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/system-users/': {
      id: '/dashboard/system-users/'
      path: '/system-users'
      fullPath: '/dashboard/system-users/'
      preLoaderRoute: typeof DashboardSystemUsersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shuttle-trips/': {
      id: '/dashboard/shuttle-trips/'
      path: '/shuttle-trips'
      fullPath: '/dashboard/shuttle-trips/'
      preLoaderRoute: typeof DashboardShuttleTripsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments/': {
      id: '/dashboard/payments/'
      path: '/payments'
      fullPath: '/dashboard/payments/'
      preLoaderRoute: typeof DashboardPaymentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hire-driver-bookings/': {
      id: '/dashboard/hire-driver-bookings/'
      path: '/hire-driver-bookings'
      fullPath: '/dashboard/hire-driver-bookings/'
      preLoaderRoute: typeof DashboardHireDriverBookingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drivers/': {
      id: '/dashboard/drivers/'
      path: '/drivers'
      fullPath: '/dashboard/drivers/'
      preLoaderRoute: typeof DashboardDriversIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/car-rental-bookings/': {
      id: '/dashboard/car-rental-bookings/'
      path: '/car-rental-bookings'
      fullPath: '/dashboard/car-rental-bookings/'
      preLoaderRoute: typeof DashboardCarRentalBookingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cab-trips/': {
      id: '/dashboard/cab-trips/'
      path: '/cab-trips'
      fullPath: '/dashboard/cab-trips/'
      preLoaderRoute: typeof DashboardCabTripsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shuttle-trips/$tripId/': {
      id: '/dashboard/shuttle-trips/$tripId/'
      path: '/shuttle-trips/$tripId'
      fullPath: '/dashboard/shuttle-trips/$tripId/'
      preLoaderRoute: typeof DashboardShuttleTripsTripIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing/shuttle/': {
      id: '/dashboard/pricing/shuttle/'
      path: '/pricing/shuttle'
      fullPath: '/dashboard/pricing/shuttle/'
      preLoaderRoute: typeof DashboardPricingShuttleIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing/model/': {
      id: '/dashboard/pricing/model/'
      path: '/pricing/model'
      fullPath: '/dashboard/pricing/model/'
      preLoaderRoute: typeof DashboardPricingModelIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing/driver-rental-rates/': {
      id: '/dashboard/pricing/driver-rental-rates/'
      path: '/pricing/driver-rental-rates'
      fullPath: '/dashboard/pricing/driver-rental-rates/'
      preLoaderRoute: typeof DashboardPricingDriverRentalRatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing/car-rentals/': {
      id: '/dashboard/pricing/car-rentals/'
      path: '/pricing/car-rentals'
      fullPath: '/dashboard/pricing/car-rentals/'
      preLoaderRoute: typeof DashboardPricingCarRentalsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing/cab-rates/': {
      id: '/dashboard/pricing/cab-rates/'
      path: '/pricing/cab-rates'
      fullPath: '/dashboard/pricing/cab-rates/'
      preLoaderRoute: typeof DashboardPricingCabRatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hire-driver-bookings/$bookingId/': {
      id: '/dashboard/hire-driver-bookings/$bookingId/'
      path: '/hire-driver-bookings/$bookingId'
      fullPath: '/dashboard/hire-driver-bookings/$bookingId/'
      preLoaderRoute: typeof DashboardHireDriverBookingsBookingIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drivers/register/': {
      id: '/dashboard/drivers/register/'
      path: '/drivers/register'
      fullPath: '/dashboard/drivers/register/'
      preLoaderRoute: typeof DashboardDriversRegisterIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/drivers/$driverId/': {
      id: '/dashboard/drivers/$driverId/'
      path: '/drivers/$driverId'
      fullPath: '/dashboard/drivers/$driverId/'
      preLoaderRoute: typeof DashboardDriversDriverIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/car-rental-bookings/sales-personnel/': {
      id: '/dashboard/car-rental-bookings/sales-personnel/'
      path: '/car-rental-bookings/sales-personnel'
      fullPath: '/dashboard/car-rental-bookings/sales-personnel/'
      preLoaderRoute: typeof DashboardCarRentalBookingsSalesPersonnelIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/car-rental-bookings/$rentalId/': {
      id: '/dashboard/car-rental-bookings/$rentalId/'
      path: '/car-rental-bookings/$rentalId'
      fullPath: '/dashboard/car-rental-bookings/$rentalId/'
      preLoaderRoute: typeof DashboardCarRentalBookingsRentalIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cab-trips/$tripId/': {
      id: '/dashboard/cab-trips/$tripId/'
      path: '/cab-trips/$tripId'
      fullPath: '/dashboard/cab-trips/$tripId/'
      preLoaderRoute: typeof DashboardCabTripsTripIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCabTripsIndexRoute: typeof DashboardCabTripsIndexRoute
  DashboardCarRentalBookingsIndexRoute: typeof DashboardCarRentalBookingsIndexRoute
  DashboardDriversIndexRoute: typeof DashboardDriversIndexRoute
  DashboardHireDriverBookingsIndexRoute: typeof DashboardHireDriverBookingsIndexRoute
  DashboardPaymentsIndexRoute: typeof DashboardPaymentsIndexRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardShuttleTripsIndexRoute: typeof DashboardShuttleTripsIndexRoute
  DashboardSystemUsersIndexRoute: typeof DashboardSystemUsersIndexRoute
  DashboardCabTripsTripIdIndexRoute: typeof DashboardCabTripsTripIdIndexRoute
  DashboardCarRentalBookingsRentalIdIndexRoute: typeof DashboardCarRentalBookingsRentalIdIndexRoute
  DashboardCarRentalBookingsSalesPersonnelIndexRoute: typeof DashboardCarRentalBookingsSalesPersonnelIndexRoute
  DashboardDriversDriverIdIndexRoute: typeof DashboardDriversDriverIdIndexRoute
  DashboardDriversRegisterIndexRoute: typeof DashboardDriversRegisterIndexRoute
  DashboardHireDriverBookingsBookingIdIndexRoute: typeof DashboardHireDriverBookingsBookingIdIndexRoute
  DashboardPricingCabRatesIndexRoute: typeof DashboardPricingCabRatesIndexRoute
  DashboardPricingCarRentalsIndexRoute: typeof DashboardPricingCarRentalsIndexRoute
  DashboardPricingDriverRentalRatesIndexRoute: typeof DashboardPricingDriverRentalRatesIndexRoute
  DashboardPricingModelIndexRoute: typeof DashboardPricingModelIndexRoute
  DashboardPricingShuttleIndexRoute: typeof DashboardPricingShuttleIndexRoute
  DashboardShuttleTripsTripIdIndexRoute: typeof DashboardShuttleTripsTripIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCabTripsIndexRoute: DashboardCabTripsIndexRoute,
  DashboardCarRentalBookingsIndexRoute: DashboardCarRentalBookingsIndexRoute,
  DashboardDriversIndexRoute: DashboardDriversIndexRoute,
  DashboardHireDriverBookingsIndexRoute: DashboardHireDriverBookingsIndexRoute,
  DashboardPaymentsIndexRoute: DashboardPaymentsIndexRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardShuttleTripsIndexRoute: DashboardShuttleTripsIndexRoute,
  DashboardSystemUsersIndexRoute: DashboardSystemUsersIndexRoute,
  DashboardCabTripsTripIdIndexRoute: DashboardCabTripsTripIdIndexRoute,
  DashboardCarRentalBookingsRentalIdIndexRoute:
    DashboardCarRentalBookingsRentalIdIndexRoute,
  DashboardCarRentalBookingsSalesPersonnelIndexRoute:
    DashboardCarRentalBookingsSalesPersonnelIndexRoute,
  DashboardDriversDriverIdIndexRoute: DashboardDriversDriverIdIndexRoute,
  DashboardDriversRegisterIndexRoute: DashboardDriversRegisterIndexRoute,
  DashboardHireDriverBookingsBookingIdIndexRoute:
    DashboardHireDriverBookingsBookingIdIndexRoute,
  DashboardPricingCabRatesIndexRoute: DashboardPricingCabRatesIndexRoute,
  DashboardPricingCarRentalsIndexRoute: DashboardPricingCarRentalsIndexRoute,
  DashboardPricingDriverRentalRatesIndexRoute:
    DashboardPricingDriverRentalRatesIndexRoute,
  DashboardPricingModelIndexRoute: DashboardPricingModelIndexRoute,
  DashboardPricingShuttleIndexRoute: DashboardPricingShuttleIndexRoute,
  DashboardShuttleTripsTripIdIndexRoute: DashboardShuttleTripsTripIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
